# Generated by Django 3.2 on 2021-05-02 08:46

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('PollID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Content', models.TextField()),
                ('Company', models.CharField(max_length=50)),
                ('CreateDateTime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('EndDateTime', models.DateTimeField()),
                ('ResultDateTime', models.DateTimeField()),
            ],
        ),
    ]
