# Generated by Django 3.2 on 2021-05-02 09:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('CompanyID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Volume', models.CharField(max_length=20)),
                ('MarketCap', models.CharField(max_length=20)),
                ('FaceValue', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='poll',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.company'),
        ),
    ]
