# Generated by Django 3.2 on 2021-05-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_alter_poll_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.company'),
        ),
    ]
