# Generated by Django 3.2 on 2021-05-04 09:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_alter_userdata_dateofbirth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('VoteID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Feedback', models.BooleanField()),
                ('Poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.poll')),
            ],
        ),
    ]
