# Generated by Django 3.2 on 2021-05-04 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0008_vote_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserCustomerMapper',
            fields=[
                ('UcmID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Avg', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.company')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
