# Generated by Django 3.2 on 2021-05-04 10:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0009_auto_20210504_1543'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCustomerMapper',
            new_name='UserCompanyMapper',
        ),
    ]
